service: cloud-functions-research-data

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  step1:
    handler: handler.step1
    timeout: 120
    memorySize: 1536
    events:
      - http:
          path: files
          method: get
          cors: true
  step2:
    handler: handler.step2
    timeout: 120
    memorySize: 1536
    events:
      - s3:
          bucket: cloud-functions-research-data-step1
          event: s3:ObjectCreated:*