service: cloud-functions-research-kkulak

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

functions:
  montecarlo:
    handler: handler.montecarlo
    timeout: 120
    memorySize: 512
    events:
      - http:
          path: pi-nodejs
          method: get
          cors: true