service: cloud-functions-research-snowak

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1



functions:
  matrixMultiplication:
    handler: handler.matrixMultiplication
    events:
      - http:
          path: multiplication
          method: post
          cors: true