service: cloud-functions-research-snowak

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  matrixMultiplication:
    handler: handler.matrixMultiplication
    timeout: 120
    memorySize: 1536
    events:
      - http:
          path: multiplication
          method: post
          cors: true