service: cloud-functions-research-kkulak

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  matrixMultiplication:
    handler: handler.matrixMultiplication
    timeout: 120
    memorySize: 512