service: kkulak-event-hub-af

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions


functions:
  matrixMultiplication:
    handler: handler.matrixMultiplication
    events:
      - http: true
        x-azure-settings:
            authLevel : anonymous
